Project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from . import views

favicon_view = RedirectView.as_view(url='/static/main/content/images/favicon.ico',
                                    permanent=True)
# import ipdb; ipdb.set_trace()
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^favicon\.ico$', favicon_view),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/', include('chat.urls')),
    url(r'^game/', include('game.urls')),
]

accounts/urls.py
from django.urls import reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.password_validation import password_validators_help_text_html as pass_help
from . import views, forms

app_name = 'accounts'
urlpatterns = [
    url(r'^register/$',
        views.register,
        name='register'),

    url(r'^register-done/$',
        views.register_done,
        name='register_done'),

    url(r'^login/$',
        auth_views.LoginView.as_view(
            template_name='accounts/login.html',
            extra_context={'title': "Login", 'submit': "Login"},
            redirect_authenticated_user=True),
        name='login'),

    # 'title' is automatically included in the context by Django here
    url(r'^logout/$',
        auth_views.LogoutView.as_view(
            template_name='accounts/success_page_login.html',
            extra_context={'message': "You have successfully logged out"}),
        name='logout'),

    url(r'^profile/$',
        views.profile,
        name='profile'),

    url(r'^change-password/$',
        views.change_password,
        name='change_password'),

    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='main/generic_form.html',
            email_template_name='accounts/password_reset_email.html',
            subject_template_name='accounts/password_reset_subject.txt',
            success_url=reverse_lazy('accounts:password_reset_done'),
            extra_context={'title': "Password Reset", 'submit': "Send Email"},),
        name='password_reset'),

    url(r'^password-reset-done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/success_page.html',
            extra_context={'title': "Password Reset Email Sent",
                           'message': "Reset password email sent successfully. "
                                      "Please check your email."}),
        name='password_reset_done'),

    url(r'^edit/$',
        views.edit,
        name='edit'),

    url(r'^activate/(?P<key>[a-f|\d]+)/$',
        views.activation,
        name='activation'),

    url(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='main/generic_form.html',
            form_class=forms.PasswordSet,
            success_url=reverse_lazy('accounts:password_reset_complete'),
            extra_context={'title': "Create a New Password",
                           'submit': "Reset Password",
                           'password_help_text': pass_help()},
        ),
        name='password_reset_confirm'),

    url(r'^password-reset-complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/success_page_login.html',
            extra_context={'title': "Password Reset Complete",
                           'message': "Password reset successfully. Please login."},
        ),
        name='password_reset_complete'),
]

chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.index, name='index'),  # The start point for index view
    url(r'^new-room/$', views.room_form, name='room_form')
]

game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'
urlpatterns = [
    url(r'^$', views.game, name='index'),
    url(r'^GameRules/', views.gameRules, name='gameRules')
]

game/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User

from . import constants as c

# Create your models here.

# class Task(models.Model):
#     name = models.CharField(max_length=c.TASK_NAME_MAX)
#     prerequisites = ArrayField(models.CharField(max_length=c.TASK_NAME_MAX))
#     delay = models.IntegerField(default=0)
#     time_to_complete = models.IntegerField()
#     category = models.CharField(max_length=c.TASK_CATEGORY_MAX)

#     def __str__(self):
#         return self.name

class Player(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    knowledge = models.ManyToManyField('Knowledge')
    tasks_completed = ArrayField(models.CharField(max_length=c.TASK_NAME_MAX))


    def __str__(self):
        return self.name

class Knowledge(models.Model):
    category = models.CharField(max_length=c.TASK_CATEGORY_MAX)
    proficiency = models.FloatField(default=1.0)

    def __str__(self):
        return self.category

class Task():
    def __init__(self, data):
        """data must be a dictionary"""
        self.name = data["name"]
        self.prerequisites = data["prerequisites"]
        self.delay = data["delay"]
        self.time_to_complete = data["time_to_complete"]
        self.category = data["category"]
        self.id = data["id"]
        self.completed = data["completed"]

    # def __str__(self):
    #     return self.name

Project/views.py
from django.shortcuts import render

def index(request):
    context = {
        'title': "Home Page",
    }
    return render(request, 'main/index.html', context)

game/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Task, Player
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
import os
from django.contrib.auth.decorators import login_required
import os.path

def getTaskList(username):
	all_tasks = list()
	if os.path.exists("game/saves/" + username + ".json"):
	# if False:
		json_file = open("game/saves/" + username + ".json","r")
	else:
		json_file = open("game/tasks.json","r")
	json_dict = json.loads(json_file.read())
	json_file.close()
	for task_data in json_dict["tasks"]:
		all_tasks.append(Task(task_data))
	return all_tasks

def saveTasks(completed, taskList, username):
	print(taskList)
	for i, task in enumerate(taskList):
		taskList[i] = task.__dict__
	for i, task in enumerate(taskList):
		if "{} ".format(task["id"]) in completed or task["id"] in completed:
			taskList[i]["completed"] = True
	with open("game/saves/" + username + ".json", "w") as json_file:
		json.dump({"tasks" : taskList}, json_file, sort_keys=False, indent=4)


@login_required()
@csrf_exempt
def game(request):
	all_tasks = getTaskList(request.user.username)

	if not Player.objects.filter(name=request.user).exists():
		player = Player(name=request.user, tasks_completed=[])
		player.save()
	else:
		player = Player.objects.get(name=request.user)

	context = {
		'title': "Game Page",
		'tasks': all_tasks,
	}

	if request.is_ajax():
		if request.method == 'POST':
			tasks_to_update = request.POST.getlist('toSubmit[]')
			saveTasks(tasks_to_update, all_tasks, request.user.username)

	return render(request, 'game/game.html', context)

@login_required()
def gameRules(request):
	if not Player.objects.filter(name=request.user).exists():
		player = Player(name=request.user, tasks_completed=[])
		player.save()
	else:
		player = Player.objects.get(name=request.user)
		player.tasks_completed = []
		player.save()

	context = {
		'title': "Game Rules Page"
	}

	return render(request, 'game/gameRules.html', context)

Project/templates/main/crispy_form.html
{% extends "main/layout.html" %}
<!--A generic form page to display a form with Bootstrap styling.-->
{% block content %}
    {% if password_help_text %}
        <div class="info">{{ password_help_text | safe }}</div>
    {% endif %}
    <div class="message info">{{ message|default:"" }}</div>
    <!--<button onclick="mock_data_org_info();">Mock Org Info</button>-->
    {% load crispy_forms_tags %}
    {% crispy form form.helper %}
    {% block forgot-password %}{% endblock %}

{% endblock %}

Project/templates/main/game.html
{% extends "main/layout.html" %}

{% block content %}

{% load staticfiles %}

    <script src="{% static 'main/scripts/game.js' %}"></script>

{% for task in tasks %}
  <a href = "#" class = "list-group-item">
  	<p><h5>{{ task.name }}</h5></p>
  	<p>Prerequisites: {{ task.prerequisites }}</p>
  	<p>{{ task.delay }}</p>
  	<p>{{ task.time_to_complete }}</p>
  	<p>{{ task.category }}</p>
  </a>

{% endfor %}

{% endblock %}

Project/templates/main/generic_form.html
{% extends "main/layout.html" %}
<!--A generic form page to display a form with Bootstrap styling.-->
{% block content %}
    {% if password_help_text %}
        <div class="info">{{ password_help_text | safe }}</div>
    {% endif %}
    <div class="message info">{{ message|default:"" }}</div>
    <!--<button onclick="mock_data_org_info();">Mock Org Info</button>-->
    {% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-default">{{ submit|default:"Submit" }}</button>
    </form>
    {% block forgot-password %}{% endblock %}

{% endblock %}

Project/templates/main/index.html
{% extends "main/layout.html" %}

{% block content %}
    {% load staticfiles %}

    <img class="imageFormat" src="http://achievementmotivationgroup.com/graphics/corporate-success.jpg" />

    <h1 class="headerFormat">Welcome to CorpGames!</h1><br>

    <h3>Who are we?</h3><br>

    <p>
        We are a website that is specially created to improve skills that businesses demand, but are not taught in the
        lecture hall.  We want to teach you skills such as leadership, communication, teamwork, and listening in a
        fun and stress free environment.
    </p><br>

    <h3>How do we educate?</h3><br>

    <p>
        Our process for teaching involves a series of fun, interactive games.  Each game has a different focus area
        and some games combine these areas for a greater overall challenge.  Most games are multiplayer, so we utilize
        chatrooms to ensure that every player can interact with each other.  We aim to disguise real challenges that
        occur in the corporate world inside of these games so you can learn how to handle them in a stress free
        environment.
    </p><br>

    <h3>How do you sign up?</h3><br>

    <p>
        Register in the upper right-hand corner to start playing today!  There is zero cost affiliated with signing up,
        we just want some basic information to let you know of updates to our site and for statistical reasons.
    </p>

{% endblock %}

Project/templates/main/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CorpGames - {{ title }}</title>
    {% load staticfiles %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/content/style.css' %}" />
    <script src="{% static 'main/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'main/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'main/scripts/main.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">CorpGames</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'admin:login' %}">Admin Login</a></li>
              <li><a href="{% url 'game:gameRules' %}">Office Simulator 9001</a></li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Chats<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="{% url 'chat:index' %}">Chat Rooms</a></li>
                      <li><a href="{% url 'chat:room_form' %}">Make New Room</a></li>
                  </ul>
              </li>
            </ul>
            {% include 'main/login_partial.html' %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

    <div class="container body-content">
        <h2>{{ title }}</h2>
        {% if messages %}
            <ul class="messages">
                {% for my_message in messages %}
                <li  class="message {% if my_message.tags %}{{ my_message.tags }}{% endif %}" >{{ my_message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <hr />
        {% block content %}{% endblock %}
    </div>

    <script src="{% static 'main/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'main/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

Project/templates/main/login_partial.html
{% if user.is_authenticated %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:profile' %}" class="navbar-brand">{{ user.username }}</a></li>
        <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
    </ul>

{% else %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'accounts:register' %}">Register</a></li>
        <li><a href="{% url 'accounts:login' %}">Log in</a></li>
    </ul>

{% endif %}