chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.index, name='index'),  # The start point for index view
    url(r'^new-room/$', views.room_form, name='room_form')
]

game/urls.py
from django.conf.urls import url
from . import views

app_name = 'game'
urlpatterns = [
    url(r'^$', views.game, name='index'),
    url(r'^GameRules/', views.gameRules, name='gameRules')
]

game/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User

from . import constants as c

# Create your models here.

# class Task(models.Model):
#     name = models.CharField(max_length=c.TASK_NAME_MAX)
#     prerequisites = ArrayField(models.CharField(max_length=c.TASK_NAME_MAX))
#     delay = models.IntegerField(default=0)
#     time_to_complete = models.IntegerField()
#     category = models.CharField(max_length=c.TASK_CATEGORY_MAX)

#     def __str__(self):
#         return self.name

class Player(models.Model):
    name = models.OneToOneField(User, on_delete=models.CASCADE)
    knowledge = models.ManyToManyField('Knowledge')
    tasks_completed = ArrayField(models.CharField(max_length=c.TASK_NAME_MAX))


    def __str__(self):
        return self.name

class Knowledge(models.Model):
    category = models.CharField(max_length=c.TASK_CATEGORY_MAX)
    proficiency = models.FloatField(default=1.0)

    def __str__(self):
        return self.category

class Task():
    def __init__(self, data):
        """data must be a dictionary"""
        self.name = data["name"]
        self.prerequisites = data["prerequisites"]
        self.delay = data["delay"]
        self.time_to_complete = data["time_to_complete"]
        self.category = data["category"]
        self.id = data["id"]
        self.completed = data["completed"]

    # def __str__(self):
    #     return self.name

game/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Task, Player
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
import json
import os
from django.contrib.auth.decorators import login_required
import os.path

def getTaskList(username):
	all_tasks = list()
	if os.path.exists("game/saves/" + username + ".json"):
	# if False:
		json_file = open("game/saves/" + username + ".json","r")
	else:
		json_file = open("game/tasks.json","r")
	json_dict = json.loads(json_file.read())
	json_file.close()
	for task_data in json_dict["tasks"]:
		all_tasks.append(Task(task_data))
	return all_tasks

def saveTasks(completed, taskList, username):
	print(taskList)
	for i, task in enumerate(taskList):
		taskList[i] = task.__dict__
	for i, task in enumerate(taskList):
		if "{} ".format(task["id"]) in completed or task["id"] in completed:
			taskList[i]["completed"] = True
	with open("game/saves/" + username + ".json", "w") as json_file:
		json.dump({"tasks" : taskList}, json_file, sort_keys=False, indent=4)


@login_required()
@csrf_exempt
def game(request):
	all_tasks = getTaskList(request.user.username)

	if not Player.objects.filter(name=request.user).exists():
		player = Player(name=request.user, tasks_completed=[])
		player.save()
	else:
		player = Player.objects.get(name=request.user)

	context = {
		'title': "Game Page",
		'tasks': all_tasks,
	}

	if request.is_ajax():
		if request.method == 'POST':
			tasks_to_update = request.POST.getlist('toSubmit[]')
			saveTasks(tasks_to_update, all_tasks, request.user.username)

	return render(request, 'game/game.html', context)

@login_required()
def gameRules(request):
	if not Player.objects.filter(name=request.user).exists():
		player = Player(name=request.user, tasks_completed=[])
		player.save()
	else:
		player = Player.objects.get(name=request.user)
		player.tasks_completed = []
		player.save()

	context = {
		'title': "Game Rules Page"
	}

	return render(request, 'game/gameRules.html', context)

game/templates/game/game.html
{% extends "main/layout.html" %}

{% block content %}

{% load staticfiles %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'main/content/game.css' %}" />
    <script src="{% static 'main/scripts/game.js' %}"></script>


<div class="container">
    <div class="row">
        <div class="col col-md-6">
        <h3>Tasks To-Do</h3>
        {% for task in tasks %}
            {% if task.prerequisites.0 == "None" %}
            	{% if task.completed == False %}
                    <a href="#" class="list-group-item todo-item" id = "{{ task.id }}" data-time = "{{ task.time_to_complete }}">
                    <p><h4>
                        Task: {{ task.name }} &emsp; Duration: {{ task.time_to_complete }}
                        &emsp; Category: {{ task.category }}</h4></p>
                    <br>
                    <p>No Prerequisites</p>
                    </a>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% for task in tasks %}
            {% if task.prerequisites.0 != "None" %}
                {% if task.completed == False %}
                    <a href = "#" class = "list-group-item todo-item" id = "{{ task.id }}" data-time = "{{ task.time_to_complete }}">
                    <p><h4>
                        Task: {{ task.name }} &emsp; Duration: {{ task.time_to_complete }}
                        &emsp; Category: {{ task.category }}</h4></p>
                    <br>
                    <p>Prerequisite(s):</p>
                    {% for prereq in task.prerequisites %}
                        <li> {{ prereq }} </li>
                    {% endfor %}
                    </a>
		        {% endif %}
            {% endif %}
        {% endfor %}
        </div>
        <div class="col col-md-6" id="today-box">
            <h3 id = "today-header">Task List for Today</h3>
            <div class = "hours-alert">Too many hours!</div>
            <button class="btn btn-primary" id="task-submit">Submit</button>
            <div id = "today-container">
            	<!-- container for tasks that will be moved here by user -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

game/templates/game/gameRules.html
{% extends "main/layout.html" %}

{% block content %}
{% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/content/gameRules.css' %}" />

    <h1 class="headerFormat">Goal:</h1><br>

    <p class="paragraphFormat">
        You and 3 others are tasked with completing the design and implementation of a room.
    </p><br>

    <h1 class="headerFormat">Description:</h1><br>

    <p class="paragraphFormat">
        You will have two weeks (game time) to complete your project.  Each day you will have 8 hours to fill with
        commitments.  You can either complete tasks or study.  Each task will have a category associated with it.
        Studying a certain category will increase the speed at which you can complete tasks of that category.
    </p><br>

    <h1 class="headerFormat">Rules and Tips:</h1><br>

    <list>
        <ul>
            <li>
                You must fill up 8 hours of your schedule.  No more, no less.
            </li>
            <br>
            <li>
                Game is over when goal is accomplished or when time is up.
            </li>
            <br>
            <li>
                You win by accomplishing the goal.  You lose by running out of time
            </li>
            <br>
            <li>
                Random variables will be inserted into game play.  Be wary.
            </li>
        </ul>
    </list>

    <br><br>

    <a href="{% url 'game:index' %}" class="btn">
        <strong>Play Game!</strong>
    </a>

    <a href="{% url 'index' %}"  class="btn">
        Go Back
    </a>

{% endblock %}